#!/bin/sh

bindir=../build/bin

case "$1" in
	"fold")
		$bindir/"sim_fold"
		;;
	"pipe")
		$bindir/"sim_pipe"
		;;
	"sfol1")
		$bindir/"sim_sfol1"
		;;
	"sfol2")
		$bindir/"sim_sfol2"
		;;
	"sfol4")
		$bindir/"sim_sfol4"
		;;
	"sfol8")
		$bindir/"sim_sfol8"
		;;
	"sfol16")
		$bindir/"sim_sfol16"
		;;
	*)
		echo "usage: test [type]"
		echo "	type - fold / pipe / sfol1 / sfol2 / sfol4 / sfol8 / sfol16"
esac
